version: '3'

services:
  django:
    build:
      context: .
      dockerfile: docker/BackendDockerfile      
    container_name: vjango_backend  
    command: ./docker/backend_setup.sh
    volumes:
      - .:/app
    ports:
      - "8002:8000"
  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: vjango_frontend
    command: ./docker/frontend_setup.sh
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    depends_on:
      - django